# -*- coding: utf-8 -*-
"""Spell output to Time Split to Encoded file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bv0_JehzYoanprRdXrxAChxIe1B5JwkH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/22 aug/Copy of input.csv_structured.csv")

df.head()

df = df.drop(0)

df.head()

(df["EventId"].nunique())

df["EventId"] = df["EventId"].astype('category')
df.dtypes

df["temp"] = df["EventId"].cat.codes
print(len(df))
(df.head())

df["temp"].nunique()

df.to_csv("/content/drive/MyDrive/22 aug/encoded_temp_1.csv")

df["time_stamp"] = pd.to_datetime(df["Time"])

df["time_stamp"]

df=df.sort_values(by='time_stamp',ascending=True)

df["time_stamp"]

df.head()

df.iloc[0]

len(df[(df["time_stamp"].diff()).dt.seconds > 0.5])

df1_halfsec=df[(df["time_stamp"].diff()).dt.seconds > 0.5]

df[(df["time_stamp"].diff()).dt.seconds > 0.5].head(10)

df1_halfsec

df1_halfsec.index

half_index_list =list(np.array(df1_halfsec.index))

half_index_list.append(len(df))

half_index_list.insert(0,0)

len(half_index_list)

df_split_list = []
for i in range(len(half_index_list)-1):
  df_split_list.append(df[half_index_list[i]:half_index_list[i+1]])

df_split_list[245]

df["temp"].value_counts()

def storedata(int: i):
   with open(r"/content/drive/MyDrive/22 aug/train_22aug1.txt", 'a') as fp:
    for item in list(df_split_list[i].temp):
        # write each item on a new line
        fp.write("%d " % item)
    fp.write("\n")
   return 0

for i in range(0,246):
  storedata(i)

df_copy = df.copy()

df_copy_split_list = []
for i in range(len(half_index_list)-1):
  df_copy_split_list.append(df_copy[half_index_list[i]:half_index_list[i+1]])

df_copy_split_list[245]

test_data=df_copy_split_list[245].iloc[1000:3000]

test_data.tail(20)

test_data["temp"].unique()

df[df["temp"]==962]

test_index=np.array(test_data.index)

test_index

l_55 = [ x for x in test_index if x%55 == 0]

l_55

len(l_55)

l_400 = [ x for x in test_index if x%400 == 0]

l_400

def intersection(lst1, lst2):
    lst3 = [value for value in lst1 if value in lst2]
    return lst3

intersection(l_55,l_400)

l_400.remove(748000)

for i in l_55:
  test_data["temp"][i] = 76

test_data.loc[16720]

for i in l_400:
  test_data["temp"][i] = 800

test_data.loc[16830:]

test_data.tail(5)

test_data["temp"][725701] = 274
test_data["temp"][725702] = 448

test_data.to_csv("/content/drive/MyDrive/22 aug/test_22aug_new.csv")

